/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.documentai.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                   */
class DocumentExtractionReleaseServiceTest{private final DocumentExtractionReleaseService s=new DocumentExtractionReleaseService();/**
                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                      */
@Test void releasesGovernedExtraction(){var r=s.assess(new DocumentExtractionReleaseService.Request("T1",true,true,true,96,90,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(DocumentExtractionReleaseService.Decision.RELEASE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@Test void pilotsOperationalGaps(){var r=s.assess(new DocumentExtractionReleaseService.Request("T2",true,true,true,96,90,true,true,true,true,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@Test void blocksUnsafeExtraction(){var r=s.assess(new DocumentExtractionReleaseService.Request("T3",false,false,false,60,90,false,false,false,false,true,true,false));assertThat(r.blockers()).hasSize(9);}}
