/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.documentai; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DocumentAiApiIntegrationTests{@Autowired MockMvc mvc;String token;/**
                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                               */
@BeforeEach void login()throws Exception{String j=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"operator\",\"password\":\"Demo@2026\"}")).andReturn().getResponse().getContentAsString();Matcher m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(j);if(!m.find())throw new AssertionError();token=m.group(1);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Test void extracts()throws Exception{mvc.perform(post("/api/ai/document/extract").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"documentNo\":\"DOC-1\",\"documentType\":\"合同\",\"ocrConfidence\":98,\"layoutConfidence\":95,\"sourceTrustScore\":96,\"totalFields\":18,\"missingRequiredFields\":0,\"signatureRequired\":true,\"signatureDetected\":true,\"duplicateFingerprint\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.decision").value("AUTO_ACCEPT"));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@Test void evaluatesFieldReviewDecision()throws Exception{mvc.perform(post("/api/enterprise/documentai/field-review-decision").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"documentId\":\"DOC-2\",\"documentType\":\"invoice\",\"schemaVersion\":\"v2\",\"fields\":[{\"name\":\"invoiceNo\",\"value\":\"INV-100\",\"confidence\":0.98,\"required\":true,\"pii\":false,\"masked\":false,\"businessRulePassed\":true}],\"minAutoConfidence\":0.9,\"duplicateDetected\":false,\"tamperDetected\":false,\"malwareScanPassed\":true,\"sourceHashVerified\":true,\"humanReviewEnabled\":true,\"extractorUserId\":\"extractor-a\",\"reviewerApproval\":false,\"finalApprovalRequired\":false,\"finalApprovalComplete\":false}" )).andExpect(status().isOk()).andExpect(jsonPath("$.data.decision").value("AUTO_RELEASE")).andExpect(jsonPath("$.data.fields[0].status").value("ACCEPT"));}}
