/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.documentai.controller;import cn.zhuatech.documentai.common.ApiResponse;import cn.zhuatech.documentai.service.DocumentExtractionReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                    */
@RestController @RequestMapping("/api/enterprise/documentai")public class DocumentExtractionReleaseController{private final DocumentExtractionReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                         */
public DocumentExtractionReleaseController(DocumentExtractionReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/extraction-release")public ApiResponse<DocumentExtractionReleaseService.Assessment>assess(@Valid @RequestBody DocumentExtractionReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
